defaults: &defaults
  adapter: mysql2
  username: root
  password:
  reconnect: true
  encoding: utf8
  pool: 5
  collation: utf8_unicode_ci

development:
  <<: *defaults
  database: qa_test_dev

test:
  <<: *defaults
  database: qa_test_test

production:
  <<: *defaults
  database: qa_test_production
